version: "3.8"

services:
  selenium-hub:
    image: selenium/hub:4.14.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.14.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - /dev/shm:/dev/shm

  test-runner:
    image: maven:3.9.4-eclipse-temurin-17
    container_name: automation-runner
    depends_on:
      - selenium-hub
      - chrome
    working_dir: /project
    volumes:
      - .:/project
      - ./allure-results:/project/allure-results
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444
      - BROWSER=chrome
      - EXECUTION_ENV=remote
    command: mvn clean test -Dbrowser=chrome -Dexecution_env=remote -Dallure.results.directory=./allure-results
